export const CHARACTER_LIST_REQUEST = 'CHARACTER_LIST_REQUEST'
export const CHARACTER_LIST_SUCCESS = 'CHARACTER_LIST_SUCCESS'
export const CHARACTER_LIST_FAIL = 'CHARACTER_LIST_FAIL'

export const CHARACTER_DETAILS_REQUEST = 'CHARACTER_DETAILS_REQUEST'
export const CHARACTER_DETAILS_SUCCESS = 'CHARACTER_DETAILS_SUCCESS'
export const CHARACTER_DETAILS_FAIL = 'CHARACTER_DETAILS_FAIL'

export const CHARACTER_DELETE_REQUEST = 'CHARACTER_DELETE_REQUEST'
export const CHARACTER_DELETE_SUCCESS = 'CHARACTER_DELETE_SUCCESS'
export const CHARACTER_DELETE_FAIL = 'CHARACTER_DELETE_FAIL'

export const CHARACTER_CREATE_REQUEST = 'CHARACTER_CREATE_REQUEST'
export const CHARACTER_CREATE_SUCCESS = 'CHARACTER_CREATE_SUCCESS'
export const CHARACTER_CREATE_FAIL = 'CHARACTER_CREATE_FAIL'
export const CHARACTER_CREATE_RESET = 'CHARACTER_CREATE_RESET'

export const CHARACTER_UPDATE_REQUEST = 'CHARACTER_UPDATE_REQUEST'
export const CHARACTER_UPDATE_SUCCESS = 'CHARACTER_UPDATE_SUCCESS'
export const CHARACTER_UPDATE_FAIL = 'CHARACTER_UPDATE_FAIL'
export const CHARACTER_UPDATE_RESET = 'CHARACTER_UPDATE_RESET'
