export const COMIC_LIST_REQUEST = 'COMIC_LIST_REQUEST'
export const COMIC_LIST_SUCCESS = 'COMIC_LIST_SUCCESS'
export const COMIC_LIST_FAIL = 'COMIC_LIST_FAIL'

export const COMIC_DETAILS_REQUEST = 'COMIC_DETAILS_REQUEST'
export const COMIC_DETAILS_SUCCESS = 'COMIC_DETAILS_SUCCESS'
export const COMIC_DETAILS_FAIL = 'COMIC_DETAILS_FAIL'

export const COMIC_DELETE_REQUEST = 'COMIC_DELETE_REQUEST'
export const COMIC_DELETE_SUCCESS = 'COMIC_DELETE_SUCCESS'
export const COMIC_DELETE_FAIL = 'COMIC_DELETE_FAIL'

export const COMIC_CREATE_REQUEST = 'COMIC_CREATE_REQUEST'
export const COMIC_CREATE_SUCCESS = 'COMIC_CREATE_SUCCESS'
export const COMIC_CREATE_FAIL = 'COMIC_CREATE_FAIL'
export const COMIC_CREATE_RESET = 'COMIC_CREATE_RESET'

export const COMIC_UPDATE_REQUEST = 'COMIC_UPDATE_REQUEST'
export const COMIC_UPDATE_SUCCESS = 'COMIC_UPDATE_SUCCESS'
export const COMIC_UPDATE_FAIL = 'COMIC_UPDATE_FAIL'
export const COMIC_UPDATE_RESET = 'COMIC_UPDATE_RESET'

export const COMIC_TOP_REQUEST = 'COMIC_TOP_REQUEST'
export const COMIC_TOP_SUCCESS = 'COMIC_TOP_SUCCESS'
export const COMIC_TOP_FAIL = 'COMIC_TOP_FAIL'
